### ISSUE TITLE
When our internet connection crash, then crash express server

### ISSUE THREAD

**Issue by acestudiooleg** [podio/podio-js#16]
/home/acestudio/server/podio/node_modules/podio-js/lib/transport.js:103
    if (res.ok === true && !err) {
           ^
TypeError: Cannot read property 'ok' of undefined
    at Object.module.exports._onResponse (/home/acestudio/server/podio/node_modules/podio-js/lib/transport.js:103:12)
    at Request.callback (/home/acestudio/server/podio/node_modules/podio-js/node_modules/superagent/lib/node/index.js:781:12)
    at ClientRequest.<anonymous> (/home/acestudio/server/podio/node_modules/podio-js/node_modules/superagent/lib/node/index.js:736:10)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:272:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:923:16
    at process._tickCallback (node.js:355:11)

**Comment by acestudiooleg** [comment]
sorry, already fixed, I need update

**Comment by dmatteo** [comment]
Cool, I'll close then.
